# Generated by Django 4.2.3 on 2023-08-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('views', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('formato', models.CharField(max_length=255)),
            ],
        ),
    ]
